### ISSUE TITLE
Daily Questions

### ISSUE THREAD

**Issue by DianeBaxter** [sdsc/sdsc-summer-institute-2015#2]
I'd like to post the daily questions here each night. Will that work for everyone?

**Comment by zonca** [comment]
Diane I think better survey monkey

**Comment by sinkovit** [comment]
If I correctly understand what you (Diane) are trying to do, I second Andrea's suggestion that you use survey monkey rather than GitHub. The latter is really meant more for communications among software developers

-- Bob

**Comment by DianeBaxter** [comment]
Yes, I figured that out after exploring it for a while. How do you want to get the compilation of the attendees' questions? I can post those on GitHub or send email.
Diane

Sent from my smarter-than-I phone.

On Aug 9, 2015, at 10:47 AM, Robert Sinkovits <notifications@github.com<mailto:notifications@github.com>> wrote:

If I correctly understand what you (Diane) are trying to do, I second Andrea's suggestion that you use survey monkey rather than GitHub. The latter is really meant more for communications among software developers

-- Bob

**Comment by zonca** [comment]
better via email
