### ISSUE TITLE
Visualization tools

### ISSUE THREAD

**Issue by achourasia** [sdsc/sdsc-summer-institute-2015#4]
Summer institute attendees please mention visualization tools that you use, in following format

VisIt: https://wci.llnl.gov/simulation/computer-codes/visit/
VisIt is an Open Source, interactive, scalable, visualization, animation and analysis tool.  VisIt is capabable of visualizing data from over 120 different scientific data formats.

**Comment by zonca** [comment]
@achourasia attendees do not receive notifications from this repo, it is only for instructors
