### ISSUE TITLE
OpenMP/MPI slides

### ISSUE THREAD

**Issue by tdsmith** [sdsc/sdsc-summer-institute-2015#7]
Hello! Would it be possible to publish the OpenMP/MPI slide deck in this repo? Thanks!

**Comment by sinkovit** [comment]
Hi Tim,

I'll be collecting the presentations from everyone who didn't post yet and put on GitHub.

-- Bob

**Comment by tdsmith** [comment]
Resolved by 74b75f7c8d3c085e8d8eb55af2c4a06967ef8b7a; thanks! :tada:
